name: angel_file_security
version: 1.0.1
description: Middleware for securing file uploads.
author: Tobe O <thosakwe@gmail.com>
environment:
  sdk: ">=1.19.0"
homepage: https://github.com/angel-dart/file_security
dependencies:
  angel_framework: ^1.0.0-dev
dev_dependencies:
  angel_test: ^1.0.0-dev
  test: ^0.12.0